### ISSUE TITLE
ERROR:asyncio:Task exception was never retrieved future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found ',)>

### ISSUE THREAD

**Issue by because-bot-fed** [freiheit/discord_feedbot#43]
"Huge" log below: (it's not really that bad) 

```

C:\discord_feedbot-master\discord_feedbot-master>python feed2discord.py
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:__main__:discordreddit: Starting up background_check_feed
INFO:__main__:Logged in as 'Reddit Aww Feed' ('259129586753732609')
INFO:__main__:discordreddit: processing feed
INFO:__main__:discordreddit:item t3_5ilukr unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
INFO:__main__:discordreddit:item t3_5iluod unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
INFO:__main__:discordreddit:item t3_5iluxf unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
INFO:__main__:discordreddit:item t3_5iluzp unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
INFO:__main__:discordreddit:item t3_5ilv50 unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
INFO:__main__:discordreddit:item t3_5ilvbp unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
INFO:__main__:discordreddit:item t3_5ilvgq unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
INFO:__main__:discordreddit:item t3_5ilvjh unseen, processing:
INFO:__main__:discordreddit:item:fresh and ready for parsing
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:310> exception=NotFound('NOT FOUND (status code: 404): 404: Not Found
',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "feed2discord.py", line 321, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): 404: Not Found
```

Any idea what's going on here and why it's not working/throwing errors? What is it saying isn't found?

**Comment by freiheit** [comment]
Sorry for the slow response; I was away for the holidays.

It looks like the error is when it's sending a message. Are you sure that the id number for the room is correct?
