### ISSUE TITLE
invalid literal for int() with base 10: '0.1'

### ISSUE THREAD

**Issue by VankkaGithub** [freiheit/discord_feedbot#49]
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<background_check_feed() done, defined at feed2discord.py:330> exception=ValueError("invalid literal for int() with base 10: '0.1'",)>
Traceback (most recent call last):
  File "E:\Python34\lib\asyncio\tasks.py", line 236, in _step
    result = next(coro)
  File "feed2discord.py", line 347, in background_check_feed
    start_skew_min = FEED.getint('start_skew_min',0.1)
  File "E:\Python34\lib\configparser.py", line 1236, in getint
    fallback=fallback)
  File "E:\Python34\lib\configparser.py", line 781, in getint
    return self._get(section, int, option, raw=raw, vars=vars)
  File "E:\Python34\lib\configparser.py", line 776, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '0.1'
Traceback (most recent call last):
  File "feed2discord.py", line 710, in <module>
    loop.run_until_complete(client.connect())
  File "E:\Python34\lib\asyncio\base_events.py", line 263, in run_until_complete
    self.run_forever()
  File "E:\Python34\lib\asyncio\base_events.py", line 236, in run_forever
    self._run_once()
  File "E:\Python34\lib\asyncio\base_events.py", line 1017, in _run_once
    event_list = self._selector.select(timeout)
  File "E:\Python34\lib\selectors.py", line 311, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "E:\Python34\lib\selectors.py", line 302, in _select
    r, w, x = select.select(r, w, w, timeout)
```
I have tried multiple versions of python allredy, latest, minimum, something in between

**Comment by freiheit** [comment]
Try pulling the latest version. I believe i fixed this in e5beb70.
