### ISSUE TITLE
Invalid version specifier in requirements.txt

### ISSUE THREAD

**Issue by joolean** [freiheit/discord_feedbot#82]
The latest version of requirements.txt (https://github.com/freiheit/discord_feedbot/commit/89bfeb3c91c67f857c8d3d20ab420e0e6b280d1e) uses a Ruby-style version specifier (`~>`) that pip doesn't understand. This leads to...

````
Traceback (most recent call last):
  File "/opt/feedbot/env/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 253, in install_req_from_line
    req = Requirement(req)
  File "/opt/feedbot/env/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8], e.msg
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'~> 2.20.'": Expected stringEnd
````

**Comment by freiheit** [comment]
I think ec21a84  should fix that. Can you check and let me know?
